// <auto-generated />
namespace Miam.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DebutSessionA15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DebutSessionA15));
        
        string IMigrationMetadata.Id
        {
            get { return "201508252027082_DebutSessionA15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
