// <auto-generated />
namespace Miam.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class suppressioncleetrangere : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(suppressioncleetrangere));
        
        string IMigrationMetadata.Id
        {
            get { return "201508251854225_suppression-cle-etrangere"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
